name: CV
channels:
  - pytorch  
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - conda-pack  
  - pytorch::pytorch 
  - torchvision 
  - torchaudio   
  - pandas
  - scikit-learn 
  - scikit-image 
  - matplotlib
  - pylint
  - gradio
  - urllib3=1.26.16
  - MarkupSafe=2.1.3  
  - pip:      
      - tensorflow-macos<2.11
      - tensorflow-metal
      - opencv-python   
            
# conda env create -f environment.yaml
